; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = experiences

[env_common]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	freetronics/BaroLibrary@^1.0.1
	sandeepmistry/LoRa@^0.8.0
	vittorioesposito/Sim800L Library Revised@^1.1.9
	makuna/DFPlayer Mini Mp3 by Makuna@^1.2.3
	bluerobotics/BlueRobotics MS5837 Library@^1.1.1
	finani/ICM42688@^1.1.0
	adafruit/Adafruit NeoPixel@^1.15.4

[env:sequenceur]
extends = env_common
build_src_filter = +<sequenceur/> +<commun/> -<experiences/>
build_flags = -D ROLE_SEQUENCEUR
lib_deps = 
	jgromes/RadioLib@^7.6.0
	arduino-libraries/Stepper@^1.1.3
	workloads/SCServo@^1.0.1
	sandeepmistry/LoRa@^0.8.0

[env:experiences]
extends = env_common
build_src_filter = +<experiences/> +<commun/> -<sequenceur/>
build_flags = -D ROLE_EXPERIENCES -D DEBUG
lib_deps = 
	jgromes/RadioLib@^7.6.0
	arduino-libraries/Stepper@^1.1.3
	workloads/SCServo@^1.0.1
	sandeepmistry/LoRa@^0.8.0
